import { Injectable } from "@angular/core";
import { Product } from "../models/product.model";

@Injectable({
  providedIn: "root",
})
export class ProductListService {
  productList: Product[] = [
    {
      id: 1,
      name: "Nokia 3 mobile",
      category: "electronics",
      sellingPrice: 900.55,
      MRPPrice: 600,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 2,
      name: "nike shoes",
      category: "wearing brands",
      sellingPrice: 800.55,
      MRPPrice: 450,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 3,
      name: "pen",
      category: "books and pens",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 4,
      name: "t shirt",
      category: "clothes",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 5,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 6,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 7,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 8,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 1,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 2,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 3,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 4,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 5,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 6,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 7,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
    {
      id: 8,
      name: "Name of Product",
      category: "Category Description and tags",
      sellingPrice: 34.55,
      MRPPrice: 60,
      image: "https://material.angular.io/assets/img/examples/shiba2.jpg",
      imageAlt: "Photo of a Shiba Inu",
    },
  ];

  getAllProducts() {
    return this.productList;
  }

  constructor() {}
}